name: QuantumEssentials
version: 1.0
author: Quantum
main: com.quantum.QuantumEssentials.Main
api-version: 1.16
commands:
  sendcords:
  msg:
  broadcast:
  i:
  kit:
  stats:
  fly:
  feed:
  heal:

    



